apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-stream9-maroon-buzzard-85
  namespace: vms-project
  labels:
    app: centos-stream9-maroon-buzzard-85
    kubevirt.io/dynamic-credentials-support: 'true'
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: centos-stream9-maroon-buzzard-85
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos-stream9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: centos-stream9-maroon-buzzard-85
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:cd:9e:00:00:03'
              masquerade: {}
              model: virtio
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: centos-stream9-maroon-buzzard-85
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: s7ay-3fd2-4qtc
              chpasswd: { expire: False }
          name: cloudinitdisk
